# Generated by Django 4.2.4 on 2023-08-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_period',
            field=models.IntegerField(null=True),
        ),
    ]
